name = "csa-112/simple-market-place"
version = "0.0.0"
compiler = "v1.0.28-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'csa-112/simple-market-place'"

[repository]
user = "csa-112"
project = "simple-market-place"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "2c529e84f7dde29816c244ac2e870f836ffc7391"
source = "github"
